#!/bin/bash

echo "${@}" >> /tmp/mcabber.log

TIMEOUT=0.08
BLINKS=10

led_on()  { echo +caps +scroll; }
led_off() { echo -all; }
lock()    { exec 200<$0; flock 200; }

if [ "$1" == "UNREAD" ]; then
    lock
    if [ ${2%% *} -eq 0 ]; then
        led_off
        rm -f /tmp/mcabber-unread-flag
    else
        touch /tmp/mcabber-unread-flag
    fi
else
    if [ "$1" == "MSG" -a "$2" != "OUT" ]; then
        if [ ! -e /tmp/mcabber-unread-flag ]; then
            exit
        fi

        if grep -q -Ff ~/.mcabber/mute <<< "$3"; then
            exit
        fi

        lock
        for i in `seq 1 $BLINKS`; do
            led_on  ; sleep $TIMEOUT
            led_off ; sleep $TIMEOUT
        done
        led_on
    fi
fi | sudo ledctl -Si
